### PR TITLE
Add entity extraction functionality

### LINKED ISSUE #13: [Extraction] Entity Extraction Functionality

### PR DESCRIPTION
**Pull request by reymyr**
1. Add classes related to NER to extract entities from text from general, paper, recruitment domain
2. Add endpoints to retrieve available domains and the entities of each domain

Closes #13

### CODE REVIEW

**Review by gdeananthap — APPROVED** [review]

**Comment by andresjerriels** [comment]
Please regenerate poetry.lock using ```poetry lock --no-update``` command

**Comment by andresjerriels** [comment]
The rest LGTM

**Comment by reymyr** [comment]
> Please regenerate poetry.lock using `poetry lock --no-update` command

Done

**Review by andresjerriels — APPROVED** [review]
LGTM

**Pull request merged**
